/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
// FILE AUTOGENERATED BY Specta. DO NOT EDIT.
export type Client = { id: string; first_name: string; last_name: string; email: string | null; phone: string | null; address: string | null; birth_date: string | null; sex: ClientSexEnum; comments: ClientComment[] }

export type ClientComment = { id: string; comment: string; created_at: string; updated_at: string | null; documents: ClientDocument[] }

export type ClientDocument = { id: string; original_name: string; extension: string }

export type ClientMutableProps = { first_name: string; last_name: string; email: string | null; phone: string | null; address: string | null; birth_date: string | null; sex: ClientSexEnum }

export type ClientSexEnum = "Male" | "Female" | "Other"

export type TauRpcClientCommandsInputTypes = { proc_name: "hello_world"; input_type: null } | { proc_name: "add_client"; input_type: { __taurpc_type: ClientMutableProps } }

export type TauRpcClientCommandsOutputTypes = { proc_name: "hello_world"; output_type: null } | { proc_name: "add_client"; output_type: null }

export type TauRpcClientEventsInputTypes = { proc_name: "event"; input_type: null }

export type TauRpcClientEventsOutputTypes = { proc_name: "event"; output_type: null }

const ARGS_MAP = {'':'{"add_client":["client"],"hello_world":[]}'}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcClientCommandsInputTypes, TauRpcClientCommandsOutputTypes],
}