name: Build

on:
  push:
    tags:        
      - 'v*'
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  create-release:  #1) Create the release
    runs-on: ubuntu-latest
    steps:
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  build: # 2) Build the release, for each OS, and upload the executables
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            CLEANUP_CMD: "npx rimraf 'release/!(*.deb|*.AppImage)'"
          - os: windows-latest
            CLEANUP_CMD: "npx rimraf release\\!(*.exe)"
          - os: macos-latest
            CLEANUP_CMD: "npx rimraf 'release/!(*.dmg)'"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup release artefacts
        run: ${{ matrix.CLEANUP_CMD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/terative_*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true